In [1]:
import numpy as np
from cholesky import *
# import sys
# default_stdout = sys.stdout
# default_stderr = sys.stderr
# import importlib
# importlib.reload(sys)
# sys.stdout = default_stdout
# sys.stderr = default_stderr
# sys.setdefaultencoding('utf-8')


In [2]:
n = 10
A = np.ones((n,n))
A = A.T @ A
A = A + np.eye(n)
A

array([[11., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 11., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 11., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 11., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 11., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 11., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 11., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 11., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 11., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 11.]])

In [3]:
scipy_cholesky(A)

array([[3.31662479, 3.01511345, 3.01511345, 3.01511345, 3.01511345,
        3.01511345, 3.01511345, 3.01511345, 3.01511345, 3.01511345],
       [0.        , 1.38169856, 0.65795169, 0.65795169, 0.65795169,
        0.65795169, 0.65795169, 0.65795169, 0.65795169, 0.65795169],
       [0.        , 0.        , 1.21498579, 0.3919309 , 0.3919309 ,
        0.3919309 , 0.3919309 , 0.3919309 , 0.3919309 , 0.3919309 ],
       [0.        , 0.        , 0.        , 1.15003506, 0.28049636,
        0.28049636, 0.28049636, 0.28049636, 0.28049636, 0.28049636],
       [0.        , 0.        , 0.        , 0.        , 1.11530374,
        0.21868701, 0.21868701, 0.21868701, 0.21868701, 0.21868701],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.09365371, 0.17928749, 0.17928749, 0.17928749, 0.17928749],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.07885793, 0.15195182, 0.15195182, 0.15195182],
       [0.        , 0.        , 0.       

In [4]:
from cholesky import *
raw_cholesky(A)

array([[3.31662479, 3.01511345, 3.01511345, 3.01511345, 3.01511345,
        3.01511345, 3.01511345, 3.01511345, 3.01511345, 3.01511345],
       [0.        , 1.38169856, 0.65795169, 0.65795169, 0.65795169,
        0.65795169, 0.65795169, 0.65795169, 0.65795169, 0.65795169],
       [0.        , 0.        , 1.21498579, 0.3919309 , 0.3919309 ,
        0.3919309 , 0.3919309 , 0.3919309 , 0.3919309 , 0.3919309 ],
       [0.        , 0.        , 0.        , 1.15003506, 0.28049636,
        0.28049636, 0.28049636, 0.28049636, 0.28049636, 0.28049636],
       [0.        , 0.        , 0.        , 0.        , 1.11530374,
        0.21868701, 0.21868701, 0.21868701, 0.21868701, 0.21868701],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.09365371, 0.17928749, 0.17928749, 0.17928749, 0.17928749],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.07885793, 0.15195182, 0.15195182, 0.15195182],
       [0.        , 0.        , 0.       

In [5]:
from cholesky import *
print("Error is",np.sum(np.abs(cholesky_blk(A) - scipy_cholesky(A))))
cholesky_blk(A)

Error is 2.0872192862952943e-14


array([[3.31662479, 3.01511345, 3.01511345, 3.01511345, 3.01511345,
        3.01511345, 3.01511345, 3.01511345, 3.01511345, 3.01511345],
       [0.        , 1.38169856, 0.65795169, 0.65795169, 0.65795169,
        0.65795169, 0.65795169, 0.65795169, 0.65795169, 0.65795169],
       [0.        , 0.        , 1.21498579, 0.3919309 , 0.3919309 ,
        0.3919309 , 0.3919309 , 0.3919309 , 0.3919309 , 0.3919309 ],
       [0.        , 0.        , 0.        , 1.15003506, 0.28049636,
        0.28049636, 0.28049636, 0.28049636, 0.28049636, 0.28049636],
       [0.        , 0.        , 0.        , 0.        , 1.11530374,
        0.21868701, 0.21868701, 0.21868701, 0.21868701, 0.21868701],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.09365371, 0.17928749, 0.17928749, 0.17928749, 0.17928749],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.07885793, 0.15195182, 0.15195182, 0.15195182],
       [0.        , 0.        , 0.       

In [6]:
print("Error is",np.sum(np.abs(cholesky_blk_nonzero(A) - scipy_cholesky(A))))
cholesky_blk_nonzero(A)

Error is 2.0872192862952943e-14


array([[3.31662479, 3.01511345, 3.01511345, 3.01511345, 3.01511345,
        3.01511345, 3.01511345, 3.01511345, 3.01511345, 3.01511345],
       [0.        , 1.38169856, 0.65795169, 0.65795169, 0.65795169,
        0.65795169, 0.65795169, 0.65795169, 0.65795169, 0.65795169],
       [0.        , 0.        , 1.21498579, 0.3919309 , 0.3919309 ,
        0.3919309 , 0.3919309 , 0.3919309 , 0.3919309 , 0.3919309 ],
       [0.        , 0.        , 0.        , 1.15003506, 0.28049636,
        0.28049636, 0.28049636, 0.28049636, 0.28049636, 0.28049636],
       [0.        , 0.        , 0.        , 0.        , 1.11530374,
        0.21868701, 0.21868701, 0.21868701, 0.21868701, 0.21868701],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.09365371, 0.17928749, 0.17928749, 0.17928749, 0.17928749],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.07885793, 0.15195182, 0.15195182, 0.15195182],
       [0.        , 0.        , 0.       

In [7]:
settings.system_name = "serial"
app: ArrayApplication = instance()
system: System = app.system

# r = system.newfun(1, 2, syskwargs={"grid_entry": (0, 0),
#                                    "grid_shape": (1, 1)})
# print(system.get(r))


X: BlockArray = app.random.random(shape=(16,), block_shape=(16,)).reshape((4, 4), block_shape=(2, 2))
Y: BlockArray = app.random.random(shape=(4, 4), block_shape=(2, 2))

print(X.get())

grid: ArrayGrid = X.grid.copy()
result: BlockArray = BlockArray(grid, system)

[[0.0596284  0.306581   0.21321215 0.16491701]
 [0.83676315 0.87970438 0.50471328 0.10545298]
 [0.42470141 0.87959472 0.25862812 0.66924339]
 [0.39831821 0.10661122 0.44504298 0.90699166]]


In [8]:
# for grid_entry in grid.get_entry_iterator():
#     x: Block = X.blocks[grid_entry]
#     y: Block = Y.blocks[grid_entry]
#     r: Block = result.blocks[grid_entry]
#     r.oid = system.add(x.oid, y.oid, syskwargs={
#         "grid_entry": grid_entry,
#         "grid_shape": grid.grid_shape
#     })

# print(bool(app.allclose(result, X+Y)))

In [9]:
# cluster_shape = np.array(settings.cluster_shape)
# for grid_entry in grid.get_entry_iterator():
#     x: Block = X.blocks[grid_entry]
#     y: Block = Y.blocks[grid_entry]
#     r: Block = result.blocks[grid_entry]
#     cluster_entry = tuple(np.array(grid_entry) % cluster_shape)
#     print(grid_entry, cluster_entry, cluster_shape)
#     options = system.get_options(cluster_entry=cluster_entry, cluster_shape=cluster_shape)
#     r.oid = system.call_with_options("add",
#                                      args=(x.oid, y.oid),
#                                      kwargs={}, options=options)

# print(bool(app.allclose(result, X+Y)))


In [17]:
def cholesky_nums(self,X):
    assert X.shape[0] == X.shape[1], "This function only accepts square matrices"
    assert X.block_shape[0] == X.block_shape[1], "This function only accepts square blocks"
    assert X.shape[0] % X.block_shape[0] == 0, "This function only accepts blocks divisble by size of matrix"
    single_block = X.shape[0] == X.block_shape[0] and X.shape[1] == X.block_shape[1]

    # Setup metadata
    full_shape = X.shape
    grid_shape = X.grid.grid_shape
    block_shape = X.block_shape

    n,b = full_shape[0], block_shape[0]
    num_blocks = grid_shape[0]
    grid = X.grid.copy()
    if single_block:
        # only one block means we do regular cholesky
        A_TL = self.cholesky(X).T
    else:
        # Must do blocked cholesky

        # cholesky on A_TL
        A_TL = BlockArray.from_blocks(X.blocks[:1, :1],(b,b), self.system)
        A_TL = self.cholesky(A_TL).T

        # A_TR = inv(A_TL).T @ A_TR
        A_TR = BlockArray.from_blocks(X.blocks[:1, 1:], (b,n-b), self.system)
        A_TL_inv_T = self.inv(A_TL).T
        A_TR = A_TL_inv_T @ A_TR

        # A_BR = A_BR - A_TR.T @ A_TR
        A_BR = BlockArray.from_blocks(X.blocks[1:, 1:],(n-b,n-b), self.system)
        A_BR = A_BR - (A_TR.T @ A_TR)

        while A_TL.shape[0] < n:
            A_TL_size = A_TL.shape[0]
            A_00 = A_TL
            if A_TL.shape[0] == n-b:
                print("Final iteration")
                print("A_TL size is {}".format(A_TL.shape))
                print("A_TR size is {}".format(A_TR.shape))
                print("A_BR size is {}".format(A_BR.shape))
                A_01 = A_TR
                A_11 = self.cholesky(A_BR).T
                A_TL = self.zeros((A_TL_size+b,A_TL_size+b),block_shape)
                for i in range(A_TL_size // b):
                    for j in range(A_TL_size // b):
                        A_TL.blocks[i,j].oid = A_00.blocks[i,j].oid

                for i in range(A_TL_size // b):
                    A_TL.blocks[i,A_TL_size//b].oid = A_01.blocks[i,0].oid
                A_TL.blocks[A_TL_size//b,A_TL_size//b].oid = A_11.blocks[0,0].oid
                print("Final iteration done")
                print("A_TL size is {}".format(A_TL.shape))
            else:
                A_01 = BlockArray.from_blocks(A_TR.blocks[:, :1], (A_TL_size,b), self.system)
                A_02 = BlockArray.from_blocks(A_TR.blocks[:, 1:], (A_TL_size,n-A_TL_size-b), self.system)
                A_11 = BlockArray.from_blocks(A_BR.blocks[:1, :1], (b,b), self.system)
                A_12 = BlockArray.from_blocks(A_BR.blocks[:1, 1:], (b,n-A_TL_size-b), self.system)
                A_22 = BlockArray.from_blocks(A_BR.blocks[1:, 1:], (n-A_TL_size-b,n-A_TL_size-b), self.system)

                A_11 = self.cholesky(A_11).T

                A_11_inv_T = self.inv(A_11).T
                A_12 = A_11_inv_T @ A_12

                A_22 = A_22 - A_12.T @ A_12

                # Get new A_TL, A_TR, A_BR
                A_TL = self.zeros((A_TL_size+b,A_TL_size+b),block_shape)
                A_TR = self.zeros((A_TL_size+b,n-A_TL_size-b),block_shape)

                for i in range(A_TL_size // b):
                    for j in range(A_TL_size // b):
                        A_TL.blocks[i,j].oid = A_00.blocks[i,j].oid

                for i in range(A_TL_size // b):
                    A_TL.blocks[i,A_TL_size//b].oid = A_01.blocks[i,0].oid

                A_TL.blocks[A_TL_size//b,A_TL_size//b].oid = A_11.blocks[0,0].oid

                for i in range(A_TL_size // b):
                    for j in range((n-A_TL_size-b)//b):
                        A_TR.blocks[i,j].oid = A_02.blocks[i,j].oid

                for j in range((n-A_TL_size-b)//b):
                    A_TR.blocks[A_TL_size // b,j].oid = A_12.blocks[0,j].oid

                A_BR = A_22
                print("One iteration done")
                print("A_TL size is {}".format(A_TL.shape))
                print("A_TR size is {}".format(A_TR.shape))
                print("A_BR size is {}".format(A_BR.shape))
    return A_TL

In [18]:
# A: BlockArray = app.ones(shape=(4,4), block_shape=(4,4))
# A = A.T @ A + app.eye(shape=(4,4), block_shape=(4,4))
# A.blocks

In [19]:
# app = instance()
# app.cholesky(A)

In [20]:
# app.cholesky_nums(A)

In [21]:
A: BlockArray = app.ones(shape=(8,8), block_shape=(4,4))
A = A.T @ A + app.eye(shape=(8,8), block_shape=(4,4))
# A.blocks

In [22]:
app.cholesky(A).T.blocks

array([[Block([[3.         0.         0.         0.        ]
 [2.66666667 1.37436854 0.         0.        ]
 [2.66666667 0.64676167 1.21267813 0.        ]
 [2.66666667 0.64676167 0.388057   1.14891253]]),
        Block([[2.66666667 0.64676167 0.388057   0.27852425]
 [2.66666667 0.64676167 0.388057   0.27852425]
 [2.66666667 0.64676167 0.388057   0.27852425]
 [2.66666667 0.64676167 0.388057   0.27852425]])],
       [Block([[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]),
        Block([[1.11464086 0.         0.         0.        ]
 [0.2174909  1.09321633 0.         0.        ]
 [0.2174909  0.1784843  1.07854778 0.        ]
 [0.2174909  0.1784843  0.15137513 1.06787213]])]], dtype=object)

In [23]:
cholesky_nums(app,A)

Final iteration
A_TL size is (4, 4)
A_TR size is (4, 4)
A_BR size is (4, 4)
Final iteration done
A_TL size is (8, 8)


BlockArray([[Block([[3.         0.         0.         0.        ]
 [2.66666667 1.37436854 0.         0.        ]
 [2.66666667 0.64676167 1.21267813 0.        ]
 [2.66666667 0.64676167 0.388057   1.14891253]])
  Block([[2.66666667 2.66666667 2.66666667 2.66666667]
 [0.64676167 0.64676167 0.64676167 0.64676167]
 [0.388057   0.388057   0.388057   0.388057  ]
 [0.27852425 0.27852425 0.27852425 0.27852425]])]
 [Block([[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]])
  Block([[1.11464086 0.         0.         0.        ]
 [0.2174909  1.09321633 0.         0.        ]
 [0.2174909  0.1784843  1.07854778 0.        ]
 [0.2174909  0.1784843  0.15137513 1.06787213]])]])

In [24]:
A: BlockArray = app.ones(shape=(16,16), block_shape=(4,4))
A = A.T @ A + app.eye(shape=(16,16), block_shape=(4,4))

In [27]:
app.cholesky(A).T.blocks

array([[Block([[4.12310563 0.         0.         0.        ]
 [3.88057    1.39326109 0.         0.        ]
 [3.88057    0.67552053 1.21854359 0.        ]
 [3.88057    0.67552053 0.39789179 1.15175111]]),
        Block([[3.88057    0.67552053 0.39789179 0.28350796]
 [3.88057    0.67552053 0.39789179 0.28350796]
 [3.88057    0.67552053 0.39789179 0.28350796]
 [3.88057    0.67552053 0.39789179 0.28350796]]),
        Block([[3.88057    0.67552053 0.39789179 0.28350796]
 [3.88057    0.67552053 0.39789179 0.28350796]
 [3.88057    0.67552053 0.39789179 0.28350796]
 [3.88057    0.67552053 0.39789179 0.28350796]]),
        Block([[3.88057    0.67552053 0.39789179 0.28350796]
 [3.88057    0.67552053 0.39789179 0.28350796]
 [3.88057    0.67552053 0.39789179 0.28350796]
 [3.88057    0.67552053 0.39789179 0.28350796]])],
       [Block([[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]),
        Block([[1.11631261 0.         0.         0.        ]
 [0.22050619 1.09431753 0.         0.    

In [28]:
cholesky_nums(app,A)

One iteration done
A_TL size is (8, 8)
A_TR size is (8, 8)
A_BR size is (8, 8)
One iteration done
A_TL size is (12, 12)
A_TR size is (12, 4)
A_BR size is (4, 4)
Final iteration
A_TL size is (12, 12)
A_TR size is (12, 4)
A_BR size is (4, 4)
Final iteration done
A_TL size is (16, 16)


BlockArray([[Block([[4.12310563 0.         0.         0.        ]
 [3.88057    1.39326109 0.         0.        ]
 [3.88057    0.67552053 1.21854359 0.        ]
 [3.88057    0.67552053 0.39789179 1.15175111]])
  Block([[3.88057    3.88057    3.88057    3.88057   ]
 [0.67552053 0.67552053 0.67552053 0.67552053]
 [0.39789179 0.39789179 0.39789179 0.39789179]
 [0.28350796 0.28350796 0.28350796 0.28350796]])
  Block([[3.88057    3.88057    3.88057    3.88057   ]
 [0.67552053 0.67552053 0.67552053 0.67552053]
 [0.39789179 0.39789179 0.39789179 0.39789179]
 [0.28350796 0.28350796 0.28350796 0.28350796]])
  Block([[3.88057    3.88057    3.88057    3.88057   ]
 [0.67552053 0.67552053 0.67552053 0.67552053]
 [0.39789179 0.39789179 0.39789179 0.39789179]
 [0.28350796 0.28350796 0.28350796 0.28350796]])]
 [Block([[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]])
  Block([[1.11631261 0.         0.         0.        ]
 [0.22050619 1.09431753 0.         0.        ]
 [0.22050619 0.18050598 